/** @file gsConfig.h

    @brief Provides preprocessor directives configuration of G+Smo

    This file is part of the G+Smo library.
    It is autogenerated from gsConfig.h.in during the cmake
    configuration of G+Smo. If you need to make changes edit the
    original file in the sources and NOT THIS FILE.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Author(s): A. Mantzaflaris
*/

#pragma once

/** Define the G+Smo version number. */
#define GISMO_VERSION    "25.7.0"
#define GISMO_MAJOR      25
#define GISMO_MINOR      7
#define GISMO_PATCH      0

/** Define default coefficient type. */
#define GISMO_COEFF_TYPE double
#ifndef real_t
#define real_t           GISMO_COEFF_TYPE
#endif

/** Define default index type. */
#define index_t          int

/** Define default dimension type. */
#define short_t          short

/** Define the file data directory. */
#define GISMO_DATA_DIR ""

/** Define the search paths. */
#define GISMO_SEARCH_PATHS ""

/** Define the file configuration directory. */
#define GISMO_CONFIG_DIR ""

/* Enabled Extensions - removed for Common module */

/* Determine if only header files should be used. */
#define GISMO_BUILD_LIB
//#define GISMO_HAS_EXTERN_TEMPLATES

/* Determine if Python module should be built. */
//#define GISMO_WITH_PYBIND11

/* Debug settings. */
//#define GISMO_WITH_XDEBUG
//#define GISMO_WITH_WARNINGS

/**
 * @name Eigen options - MUST be defined before Eigen is included
 * @{
 */

/*
   Eigen options -- these MUST be defined before Eigen is included.

   See:
   http://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html
*/

/*  Index type */
/** Eigen options -- these MUST be defined before Eigen is included.\n
   See: http://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html

   Index type
*/
#define EIGEN_DEFAULT_DENSE_INDEX_TYPE  index_t

/** Eigen options -- these MUST be defined before Eigen is included.\n
   See: http://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html

   Index type
*/
#define EIGEN_DEFAULT_SPARSE_INDEX_TYPE index_t

/** Eigen options -- these MUST be defined before Eigen is included.\n
   See: http://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html

 Matrix storage order
*/
#define EIGEN_DEFAULT_TO_COL_MAJOR

/** Eigen options -- these MUST be defined before Eigen is included.\n
  See: http://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html

  Compile-time static assertions are replaced by runtime assertions;
  this saves compilation time. */
#define EIGEN_NO_STATIC_ASSERT

/** Eigen options -- these MUST be defined before Eigen is included.\n
    See http://eigen.tuxfamily.org/dox/TopicUsingIntelMKL.html */
//#cmakedefine EIGEN_USE_MKL_ALL

//#cmakedefine EIGEN_DONT_VECTORIZE
//#cmakedefine EIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT
/**@}*/
