/** @file Config.h

    @brief Provides preprocessor directives configuration of G+Smo

    This file is part of the G+Smo library.
    It is autogenerated from Config.h.in during the cmake
    configuration of G+Smo. If you need to make changes edit the
    original file in the sources and NOT THIS FILE.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

    Author(s): A. Mantzaflaris
*/

#pragma once

/** Define the G+Smo version number. */
#define GISMO_VERSION    "1.0.0"
#define GISMO_MAJOR      1
#define GISMO_MINOR      0
#define GISMO_PATCH      0

/** Define default coefficient type. */
#define GISMO_COEFF_TYPE double

/** Define the file data directory. */
#define GISMO_DATA_DIR ""

/** Define the search paths. */
#define GISMO_SEARCH_PATHS ""

/** Define the file configuration directory. */
#define GISMO_CONFIG_DIR ""